/**
 * Re-export bridge wire-protocol types for use in the Vue app.
 *
 * Uses `export type` to avoid importing runtime code from the server-side
 * bridge module. The Vue build resolves the relative path at type-check
 * time via bundler moduleResolution; Vite tree-shakes these away in the
 * production bundle.
 */
export type {
  ClientMessage,
  RpcAgentAssistantMessage,
  RpcAgentEndEvent,
  RpcAgentMessage,
  RpcAgentStartEvent,
  RpcAgentStopReason,
  RpcAgentTextContent,
  RpcAgentThinkingContent,
  RpcAgentToolCall,
  RpcAgentToolResultMessage,
  RpcAgentUsage,
  RpcAgentUsageCost,
  RpcAgentUserMessage,
  RpcBridgeEvent,
  RpcCommand,
  RpcJsonObject,
  RpcJsonValue,
  RpcExtensionUIRequest,
  RpcExtensionUIResponse,
  RpcGitBranch,
  RpcGitRepoState,
  RpcImageContent,
  RpcQueuedMessage,
  RpcQueueUpdateEvent,
  RpcResponse,
  RpcSessionState,
  RpcSessionStats,
  RpcSessionStatsEvent,
  RpcSlashCommand,
  RpcThinkingLevel,
  RpcTreeEntry,
  RpcTreeTrackColumn,
  RpcToolArguments,
  RpcToolResultDetails,
  RpcTranscriptContent,
  RpcTranscriptContentBlock,
  RpcTranscriptImageBlock,
  RpcTranscriptImageUrlBlock,
  RpcTranscriptMessage,
  RpcTranscriptPage,
  RpcTranscriptSnapshotEvent,
  RpcTranscriptSystemBlock,
  RpcTranscriptTextBlock,
  RpcTranscriptThinkingBlock,
  RpcTranscriptToolCallBlock,
  RpcTranscriptToolResultBlock,
  RpcWorkspaceEntry,
  RpcWorkspaceFile,
  ServerMessage,
} from "../../bridge/types";
